"use client";
import { useState } from "react";
import { signOut } from "next-auth/react";
import { Activity, ArrowDown, ArrowRight, ArrowUpRight, BookOpen, CheckCircle2, ChevronRight, CircleHelp, Clock3, Eye, UserPlus, FlaskConical, FolderKanban, LayoutDashboard, LogOut, Menu, Pencil, RefreshCw, Search, Send, Users, X } from "lucide-react";
import type { Person, Project, Update, Workspace } from "@/lib/types";
import { STAGES } from "@/lib/types";
import { initials, latestByAssignment, shortDate } from "@/lib/format";
import { AssignmentEditor, AssignmentList, mutate, PersonEditor, ProjectEditor, ReportForm } from "./forms";
import { Modal } from "./modal";
import { AddMember, AdminActions, MemberHome, PreviewMember } from "./member-controls";

type View = "overview" | "projects" | "updates" | "people" | "report";
const stageClass = (stage: string) => `stage stage-${Math.max(0, STAGES.indexOf(stage as typeof STAGES[number]))}`;
function Avatar({ name, small = false }: { name: string; small?: boolean }) { return <span className={`avatar ${small ? "small" : ""}`}>{initials(name)}</span>; }

export function LabApp({ initial }: { initial: Workspace }) {
  const [data,setData]=useState(initial);
  const [view,setView]=useState<View>("overview");
  const [search,setSearch]=useState(""); const [stage,setStage]=useState(""); const [owner,setOwner]=useState("");
  const [selected,setSelected]=useState<string|null>(null); const [editing,setEditing]=useState<Project|null>(null);
  const [person,setPerson]=useState<Person|null>(null); const [mobile,setMobile]=useState(false);
  const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState("");const [setupBusy,setSetupBusy]=useState(false);
  const [addingMember,setAddingMember]=useState(false); const [choosingPreview,setChoosingPreview]=useState(false);
  const [assignmentTarget,setAssignmentTarget]=useState<{personId?:string}|null>(null);
  const [reportId,setReportId]=useState<string|undefined>();const [notice,setNotice]=useState("");
  const admin=data.identity.role==="admin";
  async function loadWorkspace(url:string) {
    const response=await fetch(url,{cache:"no-store"});const value=await response.json();
    if(!response.ok)throw new Error(value.error??"Could not load the workspace.");return value as Workspace;
  }
  async function previewMember(personId:string){
    const value=await loadWorkspace(`/api/member-preview?personId=${encodeURIComponent(personId)}`);
    setData(value);setSelected(null);setReportId(undefined);setNotice("");navigate("overview");
  }
  async function leavePreview(){try{setData(await loadWorkspace("/api/workspace"));setReportId(undefined);navigate("overview");}catch(e){setError((e as Error).message);}}
  function openReport(assignmentId?:string){setReportId(assignmentId);navigate("report");}
  async function choosePreview(personId:string){try{await previewMember(personId);}catch(e){setError((e as Error).message);}}

  async function refresh() {
    const url=data.preview?`/api/member-preview?personId=${encodeURIComponent(data.identity.personId)}`:"/api/workspace";
    setData(await loadWorkspace(url));
  }
  async function manualRefresh(){setRefreshing(true);setError("");try{await refresh();}catch(e){setError((e as Error).message);}finally{setRefreshing(false);}}
  async function setup(){setSetupBusy(true);setError("");try{await mutate("/api/setup",{});await refresh();}catch(e){setError((e as Error).message);}finally{setSetupBusy(false);}}
  function navigate(next:View){setView(next);setSearch("");setStage("");setOwner("");setMobile(false);}
  const titles:Record<View,string>={overview:admin?"Admin dashboard":"My assigned work",projects:admin?"Projects":"My projects",updates:admin?"Progress updates":"My progress updates",people:"Members & collaborators",report:"Submit a progress update"};
  const descriptions:Record<View,string>={overview:admin?"Add members, assign work, and review progress.":"Your projects, responsibilities, and next steps.",projects:"Choose a project to see its details, assigned work, and milestones.",updates:admin?"Review what members completed and where they need help.":"Your saved progress reports, newest first.",people:admin?"Manage who can sign in and what they can do.":"Find your teammates and research collaborators.",report:"Describe your progress, any blockers, and what you will do next."};
  const latest=latestByAssignment(data.updates);
  const needsHelp=latest.filter(u=>u.status==="Blocked" || u.blockers.trim());
  const recent=data.updates.filter(u=>Date.now()-new Date(u.createdAt).getTime()<7*86400000);
  const active=data.projects.filter(p=>p.pipeline!=="Accepted");
  const sorted=[...data.updates].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const filtered=data.projects.filter(p=> (!search || `${p.id} ${p.name} ${p.title}`.toLowerCase().includes(search.toLowerCase())) && (!stage || p.stage===stage) && (!owner || data.assignments.some(a=>a.projectId===p.id&&a.personId===owner)));
  const chosen=data.projects.find(p=>p.id===selected);
  const uniqueCollaborators=[...new Map(data.collaborators.map(c=>[`${c.name}|${c.affiliation}`,c])).values()];
  const nav = [{id:"overview" as View,label:admin?"Admin dashboard":"My work",icon:LayoutDashboard},{id:"projects" as View,label:admin?"Projects":"My projects",icon:FolderKanban},{id:"updates" as View,label:"Updates",icon:Activity},{id:"people" as View,label:"Members",icon:Users},...(admin&&data.assignments.some(a=>a.personId===data.identity.personId)?[{id:"report" as View,label:"Report my work",icon:Send}]:[])];
  function projectTable(rows:Project[], compact=false){return <div className="table-scroll"><table className="projects-table"><thead><tr><th>PROJECT</th><th>TEAM</th><th>STAGE</th><th>PRIORITY</th>{!compact&&<th>NEXT MILESTONE</th>}<th>LAST UPDATE</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{rows.map(p=>{
    const people=[...new Set(data.assignments.filter(a=>a.projectId===p.id).map(a=>a.personId))].map(id=>data.people.find(p=>p.id===id)?.name??id);
    const last=sorted.find(u=>u.projectId===p.id);
    return <tr key={p.id}><td><button className="project-name" onClick={()=>setSelected(p.id)}><span className="project-id">{p.id}</span><strong>{p.name}</strong></button></td><td><div className="team-cell"><div className="avatar-stack">{people.slice(0,3).map(n=><Avatar key={n} name={n} small/>)}</div><span>{people.length===1?people[0]:`${people.length} members`}</span></div></td><td><span className={stageClass(p.stage)}>{p.stage}</span></td><td><span className={`priority ${p.priority.startsWith("P1")?"high":""}`}><span className="dot"/>{p.priority.split(" - ")[0]}</span></td>{!compact&&<td className="milestone-cell">{p.milestone||"Not set"}{p.due&&<span className="muted">{shortDate(p.due)}</span>}</td>}<td><span className={last?"last-update":"muted"}>{last?shortDate(last.createdAt):"No report yet"}</span></td><td><button className="icon-button" aria-label={`View ${p.name}`} onClick={()=>setSelected(p.id)}><ChevronRight size={17}/></button></td></tr>;
  })}</tbody></table>{!rows.length&&<div className="empty-state"><Search size={28}/><h3>No matching projects</h3><p>Try a different search or filter.</p></div>}</div>;}
  function updateCard(u:Update){const p=data.projects.find(p=>p.id===u.projectId);const person=data.people.find(p=>p.id===u.personId);const a=data.assignments.find(a=>a.id===u.assignmentId);return <article className="update-card" key={u.id}><div className="update-card-head"><Avatar name={person?.name??"Member"}/><div><strong>{person?.name??"Lab member"}</strong><p>{p?.name??u.projectId} <span>· {a?.responsibility}</span></p></div><span className="update-date">{shortDate(u.createdAt)}</span></div><p className="update-progress">{u.progress}</p>{u.blockers&&<div className="blocker"><CircleHelp size={16}/><p>{u.blockers}</p></div>}{u.nextPlan&&<p className="next-plan"><strong>Next:</strong> {u.nextPlan}</p>}<span className={`report-status ${u.status==="Blocked"?"blocked":u.status==="Done"?"done":""}`}><span className="dot"/>{u.status}</span></article>;}

  return <div className="app-shell">
    {mobile&&<button aria-label="Close navigation" className="sidebar-overlay" onClick={()=>setMobile(false)}/>}
    <aside className={`sidebar ${mobile?"open":""}`}><a href="/" className="brand"><span className="brand-icon"><FlaskConical size={22}/></span><span>VE <strong>Lab</strong><small>RESEARCH WORKSPACE</small></span></a><div className="workspace-label"><span className="dot green"/>Venture Engineering Lab</div>
      <p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{nav.map(n=><button key={n.id} onClick={()=>n.id==="report"?openReport():navigate(n.id)} className={`nav-item ${view===n.id?"active":""}`} aria-current={view===n.id?"page":undefined}><n.icon size={19}/>{n.label}{n.id==="projects"&&<span className="nav-count">{data.projects.length}</span>}</button>)}</nav>
      <div className="sidebar-note"><BookOpen size={20}/><strong>{admin?"Your admin role":"Your member role"}</strong><p>{admin?"Add members, assign responsibilities, and review the lab’s progress.":"Work on your assigned responsibilities and share progress with your administrator."}</p><button onClick={()=>admin?navigate("people"):openReport()}>{admin?"Manage members":"Write an update"}<ArrowUpRight size={15}/></button></div>
      <div className="sidebar-user"><Avatar name={data.identity.name}/><div><strong>{data.identity.name}</strong><span>{admin?"Administrator":"Lab member"}</span></div>{!data.demo&&<button className="icon-button" aria-label="Sign out" onClick={()=>signOut({callbackUrl:"/"})}><LogOut size={17}/></button>}</div>
    </aside>
    <div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="mobile-toggle icon-button" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={22}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view==="report"?"Progress update":nav.find(n=>n.id===view)?.label}</strong></div><div className="topbar-right"><span className="connected-label"><span className="dot green"/>{data.demo?"Sample workspace":"Google Sheets connected"}</span><button className="icon-button" aria-label="Refresh workspace" disabled={refreshing} onClick={manualRefresh}><RefreshCw size={17} className={refreshing?"spinning":""}/></button><span className="topbar-divider"/><span className="role-badge">{admin?"ADMIN":"MEMBER"}</span></div></header>
      {data.demo&&<div className="demo-banner"><span><strong>Local sample workspace.</strong> Example updates; changes reset when the server restarts.</span>{!data.preview&&<form action="/api/demo" method="post"><input type="hidden" name="view" value={admin?"member":"admin"}/><button>{admin?"Member view":"Admin view"}<ArrowRight size={14}/></button></form>}</div>}
      {data.preview&&<section className="preview-banner" aria-label="Member preview"><div><strong><Eye size={18}/>Member preview: {data.identity.name}</strong><p>Read-only. You remain signed in as {data.preview.adminName}, the administrator.</p></div><div className="preview-controls"><select aria-label="Preview another member" value={data.identity.personId} onChange={e=>choosePreview(e.target.value)}>{data.people.filter(p=>p.role==="member").map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="button secondary" onClick={leavePreview}>Return to admin</button></div></section>}
      <main className="main-content"><div className="page-heading"><div><p className="eyebrow">{admin?"VENTURE ENGINEERING LAB":"YOUR RESEARCH WORKSPACE"}</p><h1>{titles[view]}</h1><p>{descriptions[view]}</p></div>{view!=="report"&&!data.needsSetup&&<div className="page-actions">{admin?<><button className="button secondary" onClick={()=>setChoosingPreview(true)}><Eye size={16}/>Preview member view</button><button className="button primary" onClick={()=>setAddingMember(true)}><UserPlus size={16}/>Add member</button></>:<button className="button primary" onClick={()=>openReport()}><Send size={16}/>Share progress</button>}</div>}</div>
      {error&&<div className="error global-error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError("")}><X size={16}/></button></div>}
      {notice&&<p className="success workspace-notice" role="status">{notice}<button className="icon-button" aria-label="Dismiss notice" onClick={()=>setNotice("")}><X size={16}/></button></p>}
      {data.needsSetup?<section className="panel setup-panel"><FlaskConical size={36}/><h2>Your Sheet is connected. Let’s fill it.</h2><p>Initialize the new Sheet with 15 projects, 21 responsibilities, and the people and collaborators from your workbook. Existing tracker records are never overwritten.</p><button className="button primary" disabled={setupBusy} onClick={setup}>{setupBusy?"Setting up…":"Initialize lab spreadsheet"}</button></section>:<>
      {view==="overview"&&<>
        {admin?<><AdminActions add={()=>setAddingMember(true)} assign={()=>setAssignmentTarget({})} preview={()=>setChoosingPreview(true)}/>
        <div className="stat-grid"><div className="stat-card"><div><span>Research projects</span><FolderKanban size={18}/></div><strong>{data.projects.length}<small>{active.length} active</small></strong><p>Projects tracked in this workspace</p></div><div className="stat-card"><div><span>Updates this week</span><Activity size={18}/></div><strong>{recent.length}<small>past 7 days</small></strong><p>Progress shared with the lab</p></div><div className="stat-card attention"><div><span>Need a hand</span><CircleHelp size={18}/></div><strong>{needsHelp.length}<small>latest reports</small></strong><p>Blockers and requests for help</p></div><div className="stat-card"><div><span>{admin?"Lab members":"My responsibilities"}</span><Users size={18}/></div><strong>{admin?data.people.length:data.assignments.length}<small>{admin?"working together":"assigned to you"}</small></strong><p>{admin?"One connected research team":"Your contribution to the bigger picture"}</p></div></div>
        <section className="panel pipeline-panel"><div className="section-heading"><div><h2>Projects by research stage</h2><p>Choose a stage to filter the projects.</p></div><span className="subtle-pill">{data.projects.length} projects</span></div><div className="stage-journey">{STAGES.map((s,i)=><button key={s} onClick={()=>{navigate("projects");setStage(s);}}><span className={`journey-number stage-${i}`}>{data.projects.filter(p=>p.stage===s).length}</span><span>{s}</span>{i<STAGES.length-1&&<ChevronRight size={15}/>}</button>)}</div></section>
        <div className="overview-grid"><section className="panel"><div className="section-heading"><div><h2>{admin?"Project portfolio":"My projects"}</h2><p>Projects, assigned members, and current stage.</p></div><button className="button text-button" onClick={()=>navigate("projects")}>View all<ArrowUpRight size={15}/></button></div>{projectTable(data.projects.slice(0,6),true)}</section><section className="panel attention-panel"><div className="section-heading"><div><h2>Members needing help</h2><p>Latest reports with blockers or requests.</p></div><span className="attention-count">{needsHelp.length}</span></div>{needsHelp.length?needsHelp.slice(0,4).map(u=><button key={u.id} className="attention-item" onClick={()=>setSelected(u.projectId)}><span className="attention-icon"><CircleHelp size={17}/></span><div><strong>{data.people.find(p=>p.id===u.personId)?.name} <span>· {u.projectId}</span></strong><p>{u.blockers||"Reported a blocker. Open the project for details."}</p><span>{shortDate(u.createdAt)}</span></div><ChevronRight size={15}/></button>):<div className="quiet-state"><CheckCircle2 size={28}/><h3>No blockers reported</h3><p>No open requests in the latest reports.</p></div>}<div className="panel-foot">Based on each responsibility’s latest update.</div></section></div>
        </>:<MemberHome data={data} report={openReport}/>}
        <section className="recent-section"><div className="section-heading"><div><h2>{admin?"Recent progress reports":"My recent updates"}</h2><p>{admin?"Review completed work and requests for help.":"Your own saved reports."}</p></div><button className="button text-button" onClick={()=>navigate("updates")}>All updates<ArrowUpRight size={15}/></button></div><div className="recent-grid">{sorted.slice(0,3).map(updateCard)}</div>{!sorted.length&&<div className="empty-state"><Clock3 size={26}/><p>{admin?"Reports appear here after members submit updates on their assigned work.":"No reports yet. Write an update on one of your responsibilities above."}</p></div>}</section>
      </>}
      {view==="projects"&&<section className="panel"><div className="filter-bar"><div className="search-field"><Search size={17}/><input aria-label="Search projects" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter by stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="">All stages</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select>{admin&&<select aria-label="Filter by person" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Everyone</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<span className="filter-count">{filtered.length} projects</span></div>{projectTable(filtered)}</section>}
      {view==="updates"&&<><div className="filter-bar standalone"><div className="search-field"><Search size={17}/><input aria-label="Search updates" placeholder="Search progress or blockers…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{admin&&<select aria-label="Filter updates by person" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Everyone</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<span className="filter-count"><ArrowDown size={13}/>Newest first</span></div><div className="updates-list">{sorted.filter(u=>(!owner||u.personId===owner)&&(!search||`${u.progress} ${u.blockers} ${u.projectId}`.toLowerCase().includes(search.toLowerCase()))).map(updateCard)}</div>{!sorted.length&&<div className="empty-state"><Activity size={30}/><h3>No updates yet</h3><p>Updates will appear as members share their progress.</p></div>}</>}
      {view==="report"&&<ReportForm key={`${data.identity.personId}:${reportId??"default"}`} data={data} refresh={refresh} initialAssignmentId={reportId}/>}
      {view==="people"&&<><div className="section-heading people-heading"><h2>Inside the lab <span className="subtle-pill">{data.people.length}</span></h2>{admin&&<p>Members submit updates on assigned work. Administrators manage the whole lab.</p>}</div><div className="people-grid">{data.people.map(p=><article className="person-card" key={p.id}><div className="person-head"><Avatar name={p.name}/>{admin&&<button className="icon-button" aria-label={`Edit ${p.name}`} onClick={()=>setPerson(p)}><Pencil size={16}/></button>}</div><h3>{p.name}</h3><p>{p.affiliation||"Affiliation not added"}</p><span className="person-role">{p.role==="admin"?"Administrator":"Lab member"}</span><div className="person-projects">{[...new Set(data.assignments.filter(a=>a.personId===p.id).map(a=>a.projectId))].map(id=><button key={id} onClick={()=>setSelected(id)}>{id}</button>)}</div>{p.email?<a className="person-email" href={`mailto:${p.email}`}>{p.email}</a>:<span className="person-email muted">Add a Google email to enable sign-in</span>}{admin&&<div className="person-card-actions"><button className="button secondary" aria-label={`Assign work to ${p.name}`} onClick={()=>setAssignmentTarget({personId:p.id})}>Assign work</button>{p.role==="member"&&<button className="button text-button" aria-label={`Preview ${p.name}`} onClick={()=>choosePreview(p.id)}><Eye size={14}/>Preview</button>}</div>}</article>)}</div><div className="section-heading people-heading collaborator-heading"><div><h2>Research collaborators</h2><p>Connections across projects and institutions.</p></div></div><div className="collaborator-grid">{uniqueCollaborators.map(c=><article className="collaborator-card" key={`${c.name}|${c.affiliation}`}><Avatar name={c.name}/><div><strong>{c.name}</strong><p>{c.affiliation||"Affiliation not added"}</p><span>{[...new Set(data.collaborators.filter(other=>other.name===c.name&&other.affiliation===c.affiliation).map(other=>other.projectId))].join(" · ")}</span></div></article>)}</div></>}
      </>}
      <footer className="workspace-footer"><span><FlaskConical size={13}/>VE Lab · A home for work in progress</span><span>{data.demo?"Local sample data":"Your research lives in Google Sheets"}</span></footer></main>
    </div>
    {chosen&&<Modal title={`${chosen.id} · Project details`} close={()=>setSelected(null)}><div className="modal-body project-detail"><div className="detail-title"><div><span className={stageClass(chosen.stage)}>{chosen.stage}</span><h2>{chosen.name}</h2><p>{chosen.title}</p></div>{admin&&<button className="button secondary" onClick={()=>{setEditing(chosen);setSelected(null);}}><Pencil size={15}/>Edit</button>}</div><div className="detail-facts"><div><span>Priority</span><strong>{chosen.priority}</strong></div><div><span>Publication</span><strong>{chosen.pipeline}</strong></div><div><span>Target journal</span><strong>{chosen.journal||"Not set"}</strong></div><div><span>Target conference</span><strong>{chosen.conference||"Not set"}</strong></div></div><div className="milestone-note"><p className="eyebrow">NEXT MILESTONE</p><strong>{chosen.milestone||"Not set yet"}</strong>{chosen.due&&<span>Due {shortDate(chosen.due)}</span>}</div><AssignmentList data={data} projectId={chosen.id} refresh={refresh}/>{chosen.methods&&<section className="detail-section"><h3>Research methods</h3><p>{chosen.methods}</p></section>}{data.collaborators.some(c=>c.projectId===chosen.id)&&<section className="detail-section"><h3>Collaborators</h3>{data.collaborators.filter(c=>c.projectId===chosen.id).map(c=><p key={c.id}><strong>{c.name}</strong>{c.affiliation&&` · ${c.affiliation}`}</p>)}</section>}{chosen.notes&&<section className="detail-section"><h3>Notes</h3><p>{chosen.notes}</p></section>}<section className="detail-section"><h3>Progress history</h3>{sorted.filter(u=>u.projectId===chosen.id).map(updateCard)}{!sorted.some(u=>u.projectId===chosen.id)&&<p className="muted">No reports yet.</p>}</section></div></Modal>}
    {editing&&<ProjectEditor project={editing} close={()=>setEditing(null)} saved={refresh}/>}{person&&<PersonEditor person={person} protectedAccount={data.protectedPersonIds?.includes(person.id)} close={()=>setPerson(null)} saved={refresh}/>}
    {addingMember&&admin&&<AddMember close={()=>setAddingMember(false)} saved={async(person)=>{await refresh();navigate("people");setNotice(`${person.name} added. Choose Assign work on their card so they can submit updates.`);}}/>}
    {choosingPreview&&admin&&<PreviewMember data={data} close={()=>setChoosingPreview(false)} preview={previewMember}/>}
    {assignmentTarget&&admin&&<AssignmentEditor data={data} personId={assignmentTarget.personId} close={()=>setAssignmentTarget(null)} saved={async()=>{await refresh();setNotice("Responsibility assigned. Preview the member’s view to check their project and update form.");}}/>}
  </div>;
}
