"use client";
import { useState, useSyncExternalStore } from "react";
import { signOut } from "next-auth/react";
import { Activity, ArrowRight, CheckCircle2, CircleHelp, Copy, Eye, FlaskConical, FolderKanban, LogOut, Pencil, Plus, RefreshCw, Search, Users, X } from "lucide-react";
import type { Person, Project, Update, Workspace } from "@/lib/types";
import { initials, latestByAssignment, shortDate } from "@/lib/format";
import { AssignmentList, mutate, PersonEditor, ProjectEditor } from "./forms";
import { EntryForm } from "./entry-form";
import { Modal } from "./modal";

const subscribeReady=()=>()=>{};
const clientReady=()=>true;
const serverReady=()=>false;
function Avatar({name}:{name:string}){return <span className="avatar">{initials(name)}</span>;}
export function LabApp({initial}:{initial:Workspace}){
  const ready=useSyncExternalStore(subscribeReady,clientReady,serverReady);
  const [data,setData]=useState(initial);const [search,setSearch]=useState("");const [personFilter,setPersonFilter]=useState("");
  const [statusFilter,setStatusFilter]=useState("");const [limit,setLimit]=useState(20);
  const [entry,setEntry]=useState<{assignmentId?:string}|null>(null);
  const [selected,setSelected]=useState<string|null>(null);const [editing,setEditing]=useState<Project|null>(null);const [person,setPerson]=useState<Person|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const admin=data.identity.role==="admin";
  async function load(url:string){const response=await fetch(url,{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error??"Could not load the lab.");return value as Workspace;}
  async function refresh(){setData(await load(data.preview?`/api/member-preview?personId=${encodeURIComponent(data.identity.personId)}`:"/api/workspace"));}
  async function manualRefresh(){setBusy(true);setError("");try{await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function setup(){setBusy(true);setError("");try{await mutate("/api/setup",{});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function preview(personId:string){try{setData(await load(`/api/member-preview?personId=${encodeURIComponent(personId)}`));setSearch("");setPersonFilter("");setStatusFilter("");setLimit(20);setNotice("");}catch(e){setError((e as Error).message);}}
  async function returnToAdmin(){try{setData(await load("/api/workspace"));setEntry(null);setSearch("");setNotice("");}catch(e){setError((e as Error).message);}}
  async function copyLink(){try{await navigator.clipboard.writeText(window.location.origin);setNotice("Link copied. Share it with the lab—people can sign in and add their own entries.");}catch{setError("Copy the website address from your browser and share it with the lab.");}}
  const sorted=[...data.updates].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const latest=latestByAssignment(data.updates);const blocked=latest.filter(u=>u.status==="Blocked"||u.blockers.trim());
  const filtered=sorted.filter(u=>(!personFilter||u.personId===personFilter)&&(!statusFilter||(statusFilter==="Blocked"?(u.status==="Blocked"||Boolean(u.blockers.trim())):u.status===statusFilter))&&(!search||`${data.people.find(p=>p.id===u.personId)?.name} ${data.projects.find(p=>p.id===u.projectId)?.name} ${u.progress} ${u.blockers}`.toLowerCase().includes(search.toLowerCase())));
  const own=data.assignments.filter(a=>a.personId===data.identity.personId);const chosen=data.projects.find(p=>p.id===selected);
  function updateCard(update:Update){const author=data.people.find(p=>p.id===update.personId);const project=data.projects.find(p=>p.id===update.projectId);return <article className="update-card" key={update.id}><div className="update-card-head"><Avatar name={author?.name??"Member"}/><div><strong>{author?.name??"Member"}</strong><p><button className="inline-project" onClick={()=>setSelected(update.projectId)}>{project?.name??"Project"}</button></p></div><span className="update-date">{shortDate(update.createdAt)}</span></div><p className="update-progress">{update.progress}</p>{update.blockers&&<div className="blocker"><CircleHelp size={16}/><p>{update.blockers}</p></div>}{update.nextPlan&&<p className="next-plan"><strong>Next:</strong> {update.nextPlan}</p>}<span className={`report-status ${update.status==="Blocked"?"blocked":update.status==="Done"?"done":""}`}>{update.status}</span></article>;}
  return <div className="simple-app">
    <header className="simple-topbar"><a className="brand" href="/"><span className="brand-icon"><FlaskConical size={22}/></span><span>VE <strong>Lab</strong></span></a><div className="simple-account"><span>{data.identity.name}</span><span className="role-badge">{admin?"ADMIN":"MEMBER"}</span><button className="icon-button" aria-label="Refresh workspace" disabled={busy} onClick={manualRefresh}><RefreshCw size={18}/></button>{!data.demo&&<button className="icon-button" aria-label="Sign out" onClick={()=>signOut({callbackUrl:"/"})}><LogOut size={18}/></button>}</div></header>
    {data.demo&&<div className="demo-banner"><span><strong>Local sample workspace.</strong> Example data; changes reset when the server restarts.</span>{!data.preview&&<div className="sample-actions"><form action="/api/demo" method="post"><input type="hidden" name="view" value={admin?"member":"admin"}/><button>{admin?"Member view":"Admin view"}<ArrowRight size={14}/></button></form>{admin&&<form action="/api/demo" method="post"><input type="hidden" name="view" value="new"/><button>New member view<ArrowRight size={14}/></button></form>}</div>}</div>}
    {data.preview&&<section className="preview-banner" aria-label="Member preview"><div><strong><Eye size={18}/>Member preview: {data.identity.name}</strong><p>Read-only. You remain signed in as {data.preview.adminName}.</p></div><button className="button secondary" onClick={returnToAdmin}>Return to admin</button></section>}
    <main className="simple-main"><div className="page-heading"><div><p className="eyebrow">VENTURE ENGINEERING LAB</p><h1>{admin?"Lab overview":"My work"}</h1><p>{admin?"Everyone’s work, progress, and blockers in one place.":"Add your work and keep track of your progress."}</p></div>{!data.needsSetup&&<div className="page-actions">{admin&&<button disabled={!ready} className="button secondary" onClick={copyLink}><Copy size={16}/>Copy invite link</button>}<button disabled={!ready} className="button primary" onClick={()=>setEntry({})}><Plus size={17}/>Add entry</button></div>}</div>
    {error&&<div className="error global-error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError("")}><X size={16}/></button></div>}{notice&&<p className="success workspace-notice" role="status">{notice}<button className="icon-button" aria-label="Dismiss notice" onClick={()=>setNotice("")}><X size={16}/></button></p>}
    {data.needsSetup?<section className="panel setup-panel"><FlaskConical size={36}/><h2>Prepare the lab once</h2><p>Initialize the spreadsheet, then share the website. Members can sign in and add their own work.</p><button className="button primary" disabled={busy} onClick={setup}>{busy?"Setting up…":"Initialize lab spreadsheet"}</button></section>:<>
    {admin?<>
      <section className="share-note"><CheckCircle2 size={21}/><p><strong>Share the link. Members do the rest.</strong> Their Google sign-in creates an account. They choose a project and add entries themselves.</p></section>
      <div className="stat-grid"><div className="stat-card"><div><span>People</span><Users size={18}/></div><strong>{data.people.length}</strong></div><div className="stat-card"><div><span>Projects</span><FolderKanban size={18}/></div><strong>{data.projects.length}</strong></div><div className="stat-card"><div><span>Entries</span><Activity size={18}/></div><strong>{data.updates.length}</strong></div><div className="stat-card attention"><div><span>Need help</span><CircleHelp size={18}/></div><strong>{blocked.length}</strong></div></div>
      <section className="panel roster-panel"><div className="section-heading"><div><h2>People and their work</h2><p>Accounts appear automatically after Google sign-in. Imported workbook people remain listed.</p></div></div><div className="table-scroll"><table className="roster-table"><thead><tr><th>Person</th><th>Projects</th><th>Latest entry</th><th>Status</th><th><span className="sr-only">Member tools</span></th></tr></thead><tbody>{data.people.map(p=>{
        const last=sorted.find(u=>u.personId===p.id);const projects=data.projects.filter(project=>data.assignments.some(a=>a.personId===p.id&&a.projectId===project.id));
        return <tr key={p.id}><td><div className="roster-person"><Avatar name={p.name}/><div><strong>{p.name}</strong><span>{p.email||"Imported from workbook"}</span></div></div></td><td>{projects.length?projects.map(project=><button key={project.id} className="roster-project" onClick={()=>setSelected(project.id)}>{project.name}</button>):<span className="muted">No entries yet</span>}</td><td>{last?shortDate(last.createdAt):"No entry yet"}</td><td>{last?<span className={`report-status ${last.status==="Blocked"?"blocked":""}`}>{last.status}</span>:<span className="muted">—</span>}</td><td><div className="roster-tools"><button disabled={!ready} className="icon-button" aria-label={`Edit ${p.name}`} onClick={()=>setPerson(p)}><Pencil size={16}/></button>{p.role==="member"&&<button disabled={!ready} className="icon-button" aria-label={`Preview ${p.name}`} onClick={()=>preview(p.id)}><Eye size={16}/></button>}</div></td></tr>;
      })}</tbody></table></div></section>
    </>:<>
      {!own.length?<section className="panel first-entry"><h2>Welcome, {data.identity.name}.</h2><p>Your account is ready. Choose an existing project or create your own when you add an entry.</p><button disabled={!ready} className="button primary" onClick={()=>setEntry({})}><Plus size={17}/>Add your first entry</button></section>:<div className="member-work-grid">{own.map(a=>{const project=data.projects.find(p=>p.id===a.projectId);return <article className="panel member-work-card" key={a.id}><h2>{project?.name??"Project"}</h2>{a.responsibility!=="Project work"&&<p>{a.responsibility}</p>}{project?.milestone&&<p><strong>Next milestone:</strong> {project.milestone}</p>}<button disabled={!ready} className="button primary" aria-label={`Add entry for ${project?.name??a.projectId} ${a.responsibility}`} onClick={()=>setEntry({assignmentId:a.id})}><Plus size={16}/>Add entry</button></article>;})}</div>}
    </>}
    <section className="entries-section"><div className="section-heading"><div><h2>{admin?"All entries":"My entries"}</h2><p>{admin?"See who is making progress and who needs help.":"Your saved progress, newest first."}</p></div></div><div className="filter-bar standalone"><div className="search-field"><Search size={17}/><input disabled={!ready} aria-label="Search entries" placeholder={admin?"Search people, projects, or progress…":"Search your entries…"} value={search} onChange={e=>{setSearch(e.target.value);setLimit(20);}}/></div>{admin&&<select disabled={!ready} aria-label="Filter by person" value={personFilter} onChange={e=>{setPersonFilter(e.target.value);setLimit(20);}}><option value="">Everyone</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<select disabled={!ready} aria-label="Filter by status" value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setLimit(20);}}><option value="">All statuses</option><option>On track</option><option>Blocked</option><option>Done</option></select></div><div className="entries-grid">{filtered.slice(0,limit).map(updateCard)}</div>{!filtered.length&&<div className="empty-state"><Activity size={27}/><h3>{search||personFilter||statusFilter?"No matching entries":"No entries yet"}</h3><p>{search||personFilter||statusFilter?"Try a different search or filter.":admin?"Entries will appear here as members add their work.":"Use Add entry to share your first update."}</p></div>}{filtered.length>limit&&<button className="button secondary load-more" onClick={()=>setLimit(limit+20)}>Show more entries</button>}</section>
    {admin&&<details className="panel project-directory"><summary>Projects ({data.projects.length})</summary><div className="project-directory-list">{data.projects.map(p=><button key={p.id} onClick={()=>setSelected(p.id)}><strong>{p.name}</strong><span>{p.stage}</span></button>)}</div></details>}
    </>}
    <footer className="workspace-footer"><span>VE Lab</span><span>{data.demo?"Local sample data":"Saved in Google Sheets"}</span></footer></main>
    {entry&&<EntryForm data={data} initialAssignmentId={entry.assignmentId} close={()=>setEntry(null)} saved={async()=>{await refresh();setNotice(data.demo?"Entry saved in the local sample workspace.":"Entry saved to Google Sheets.");}}/>}
    {person&&admin&&<PersonEditor person={person} protectedAccount={data.protectedPersonIds?.includes(person.id)} close={()=>setPerson(null)} saved={refresh}/>}
    {editing&&admin&&<ProjectEditor project={editing} close={()=>setEditing(null)} saved={refresh}/>}
    {chosen&&<Modal title={chosen.name} close={()=>setSelected(null)}><div className="modal-body project-detail"><div className="detail-title"><div><span className="subtle-pill">{chosen.stage}</span><h2>{chosen.name}</h2>{chosen.title&&<p>{chosen.title}</p>}</div>{admin&&<button className="button secondary" onClick={()=>{setEditing(chosen);setSelected(null);}}><Pencil size={15}/>Edit project</button>}</div>{chosen.milestone&&<div className="milestone-note"><strong>Next milestone: {chosen.milestone}</strong>{chosen.due&&<span>Due {shortDate(chosen.due)}</span>}</div>}<details className="detail-section"><summary>Research details</summary><div className="detail-facts"><div><span>Publication</span><strong>{chosen.pipeline}</strong></div><div><span>Priority</span><strong>{chosen.priority}</strong></div>{chosen.journal&&<div><span>Journal</span><strong>{chosen.journal}</strong></div>}{chosen.conference&&<div><span>Conference</span><strong>{chosen.conference}</strong></div>}</div>{chosen.methods&&<p>{chosen.methods}</p>}{data.collaborators.filter(c=>c.projectId===chosen.id).map(c=><p key={c.id}>{c.name}{c.affiliation?` · ${c.affiliation}`:""}</p>)}</details><AssignmentList data={data} projectId={chosen.id} refresh={refresh}/>{chosen.notes&&<section className="detail-section"><h3>Notes</h3><p>{chosen.notes}</p></section>}<section className="detail-section"><h3>Entries</h3>{sorted.filter(u=>u.projectId===chosen.id).map(updateCard)}{!sorted.some(u=>u.projectId===chosen.id)&&<p className="muted">No entries yet.</p>}</section></div></Modal>}
  </div>;
}
